function Months() {
    return (
        <>
        <h1>Miesiące</h1>
        <ol>
            <li>
                Styczeń
                <p>31</p>
            </li>
            <li>
                Luty
                <p>28/29</p>
            </li>
            <li>
                Marzec
                <p>31</p>
            </li>
            <li>
                Kwiecień
                <p>30</p>
            </li>
            <li>
                Maj
                <p>31</p>
            </li>
            <li>
                Czerwiec
                <p>30</p>
            </li>
            <li>
                Lipiec
                <p>31</p>
            </li>
            <li>
                Sierpień
                <p>31</p>
            </li>
            <li>
                Wrzesień
                <p>30</p>
            </li>
            <li>
                Październik
                <p>31</p>
            </li>
            <li>
                Listopad
                <p>30</p>
            </li>
            <li>
                Grudzień
                <p>31</p>
            </li>
        </ol>
        </>
    );
}

export default Months;